[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "full"] }
topcoat = "0.4.0"
toasty = { version = "0.9.0", features = ["postgresql"] }
toasty-driver-postgresql = "0.9.0"
serde = { version = "1.0.229", features = ["derive"] }
